/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ArcgisAssetTracker {
    }
    interface ArcgisAssetTrackerPanel {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLArcgisAssetTrackerElement extends Components.ArcgisAssetTracker, HTMLStencilElement {
    }
    var HTMLArcgisAssetTrackerElement: {
        prototype: HTMLArcgisAssetTrackerElement;
        new (): HTMLArcgisAssetTrackerElement;
    };
    interface HTMLArcgisAssetTrackerPanelElement extends Components.ArcgisAssetTrackerPanel, HTMLStencilElement {
    }
    var HTMLArcgisAssetTrackerPanelElement: {
        prototype: HTMLArcgisAssetTrackerPanelElement;
        new (): HTMLArcgisAssetTrackerPanelElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "arcgis-asset-tracker": HTMLArcgisAssetTrackerElement;
        "arcgis-asset-tracker-panel": HTMLArcgisAssetTrackerPanelElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ArcgisAssetTracker {
    }
    interface ArcgisAssetTrackerPanel {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "arcgis-asset-tracker": ArcgisAssetTracker;
        "arcgis-asset-tracker-panel": ArcgisAssetTrackerPanel;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "arcgis-asset-tracker": LocalJSX.ArcgisAssetTracker & JSXBase.HTMLAttributes<HTMLArcgisAssetTrackerElement>;
            "arcgis-asset-tracker-panel": LocalJSX.ArcgisAssetTrackerPanel & JSXBase.HTMLAttributes<HTMLArcgisAssetTrackerPanelElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
